DROP TABLE IF EXISTS locations;

CREATE TABLE locations (
    location_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_street_number INTEGER,
    location_street_name TEXT,
    location_city TEXT,
    location_state TEXT,
    location_country TEXT,
    location_postcode TEXT,
    location_coordinates_latitude REAL,
    location_coordinates_longitude REAL,
    location_timezone_offset INTEGER,
    location_timezone_description TEXT,
);

DROP TABLE IF EXISTS pictures;

CREATE TABLE pictures (
    picture_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    picture_large TEXT,
    picture_medium TEXT,
    picture_thumbnail TEXT
);

DROP TABLE IF EXISTS persons;

CREATE TABLE persons (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gender TEXT,
    email TEXT,
    nat VARCHAR(2),
    name_title VARCHAR(4),
    name_first TEXT,
    name_last TEXT,
    dob_date TIMESTAMP,
    dob_age INTEGER,
    id_name TEXT,
    id_value TEXT,
    location_id INTEGER references locations(location_id),
    picture_id INTEGER references pictures(picture_id)
);